### ISSUE TITLE
Error loading plugins

### ISSUE THREAD

**Issue by Kirbeast** [soopercool101/BrawlCrateSamplePlugins#1]
I get these errors every time I open BrawlCrate. I'm on the Experimental updates
Example Parser (RFNT).py Error Loading plugin or loader - No module named struct
Shift UVs.py Error Loading plugin or loader - No module named struct

**Comment by soopercool101** [comment]
Make sure you have python installed and its path set in your BrawlCrate settings.

**Comment by Kirbeast** [comment]
That fixed my issue. Thank you!
